gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#9399b2"
    optionsTextColor:
      - "#B4BEFE"
    selectedLineBgColor:
      - "#2a2b3c"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#EBA0AC"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#F2CDCD"
  spinner:
    frames:
      - "⣉"
      - "⢣"
      - "⠶"
      - "⡜"
    rate: 100

  authorColors:
    "*": "#b4befe"
